### ISSUE TITLE
Avoiding copies and inefficient lists in the undirected_graph

### ISSUE THREAD

**Issue by daniel-j-h** [jcoupey/vroom#13]
I just came around your project and skimmed the code. Good job over all! :)

Here are two minor details I found:

The `undirected_graph`'s constructor takes a `matrix<T>` by value:

https://github.com/jcoupey/vroom/blob/dc008cd6fdae3b741c1b071a0447f615e75c52ac/src/structures/undirected_graph.h#L39

From what I can tell, you only need a read-only view on the matrix, so taking it by-values creates an unnecessary copy of the matrix. Taking the matrix by `const &` would suffice for that.

A few lines below the second constructor takes  the edges by value and then stores a copy in the member sink attribute:

https://github.com/jcoupey/vroom/blob/dc008cd6fdae3b741c1b071a0447f615e75c52ac/src/structures/undirected_graph.h#L55-L56

This also creates an unnecessary copy that you could avoid by moving the edges into their sink, like `_edges{std::move(edges)}`. From what I can tell you are only using `std::list` to efficiently insert at the front, in the matrix-taking constructor. If that is the only reason, then I guess it is more efficient to just use a contiguous `std::vector`, insert at the end and reverse it once. That is, I would try to avoid `std::list` where ever possible, and prefer contiguous containers like `std::vector`.

Hope that helps,
Daniel J H

**Comment by jcoupey** [comment]
Thanks Daniel for the hints. Your input is really appreciated as I'm trying to be quite strict on code efficiency and data structure choices.

Regarding the use of `std::vector` over `std::list`, it could be even more obvious since I'm not quite sure that inserting at the front is really required here. Will need a closer look as I wrote the `edge` and `undirected_graph` structures a few months back.
